# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# action 이름
name: deploy

# action 트리거 조건 (main 브랜치에 푸쉬될 때)
on:
  push:
    branches: [main]
  workflow_dispatch:

# action 동작
jobs:
  # OS 환경
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: test
        run: echo "test"
